name: ShareXin
title: ShareXin - ShareX for Linux and FreeBSD
description: ShareX-like application that lets you take a screenshot, and send it to either Twitter, a Mastodon instance, or Imgur.
url: https://sharexin.github.io
author: TheBitStick
github: https://github.com/ShareXin/ShareXin
twitter: makotoadmirer
googleAnalyticsId: UA-105358353-1
addThisId:

encoding: utf-8
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM